### PR TITLE
Add support for Python 3.10-3.11, drop EOL 2.7-3.6

### LINKED ISSUE #5: GHA fails for Python 2.7 and 3.5
It seems the current version of `paste.deploy` no longer supports Python < 3.6.

See https://github.com/zopefoundation/zope.paste/actions/runs/3307004634/jobs/5458310472

Proposed solution: Drop support for Python < 3.6 as `zope.paste` does not seem to be very widely used and we have to drop support for that ancient versions anyway in the future.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/zopefoundation/zope.paste/issues/5.

Python 2.7-3.6 are EOL and no longer receiving security updates (or any updates) from the core Python team.

| cycle |  release   | latest | latest release |    eol     |
|:------|:----------:|:-------|:--------------:|:----------:|
| 3.11  | 2022-10-24 | 3.11.0 |   2022-10-24   | 2027-10-24 |
| 3.10  | 2021-10-04 | 3.10.8 |   2022-10-11   | 2026-10-04 |
| 3.9   | 2020-10-05 | 3.9.15 |   2022-10-11   | 2025-10-05 |
| 3.8   | 2019-10-14 | 3.8.15 |   2022-10-11   | 2024-10-14 |
| 3.7   | 2018-06-26 | 3.7.15 |   2022-10-10   | 2023-06-27 |
| 3.6   | 2016-12-22 | 3.6.15 |   2021-09-03   | 2021-12-23 |
| 3.5   | 2015-09-12 | 3.5.10 |   2020-09-05   | 2020-09-13 |
| 2.7   | 2010-07-03 | 2.7.18 |   2020-04-19   | 2020-01-01 |

Also add support for Python 3.10 and 3.11.

* Python 3.10 was [released on 2021-10-04](https://discuss.python.org/t/python-3-10-0-is-now-available/10955).
* Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk).

[image](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)

### CODE REVIEW

**Comment by mgedmin** [comment]
Thank you for your PR!

Some of the files you've modified are generated from a [template shared by multiple zopefoundation repositories](https://github.com/zopefoundation/meta/tree/master/config), so the changes will be lost when we next update it.

There have been people arguing against dropping Python 2 support [unless it becomes painful](https://www.zope.dev/developer/python2.html), going as far as to volunteer to take a look at any Python 2 specific issues to reduce the maintenance burden for other volunteer maintainers.  (I think that was @jamadden?  Are you still interested in Python 2?)

**Comment by dataflake** [comment]
There's a few issues with this PR:

- It looks like you have not signed the contributor agreement yet, please see https://www.zope.dev/developer/becoming-a-committer.html. We cannot accept contributions unless we have a signed contributor agreement.
- As @mgedmin mentioned, some of the changes are to files that are managed by a separate tool and should not be modified manually. You can find information about it at https://github.com/zopefoundation/meta/tree/master/config. Essentially, you edit the file `.meta.toml` in this package and then run the tool over it.
- In the zopefoundation organization we have a policy of only removing support for older Python versions when it becomes painful to support it, which does not necessarily correlate with a Python version reaching EOL status. This is a small package and there's no pain at all in keeping this support, so please remove all those changes.

**Comment by dataflake** [comment]
After looking at https://github.com/zopefoundation/zope.paste/issues/5, which implies that @icemac is OK with dropping support for Python < 3.6 I'll modify my last point: Please remove dropping Python 3.6. Only drop Python 2.7 and 3.5. The first two points are still valid.

**Comment by hugovk** [comment]
Hi! I think I'll pass on the CLA this time and close this PR. These changes are fairly trivial and pretty similar to what you already have at https://www.zope.dev/developer/python2.html#how-to-drop-support. Thanks again!

**Pull request closed without merging**
