### PR TITLE
Drop Python 2.7 and 3.5 support

### LINKED ISSUE #5: GHA fails for Python 2.7 and 3.5
It seems the current version of `paste.deploy` no longer supports Python < 3.6.

See https://github.com/zopefoundation/zope.paste/actions/runs/3307004634/jobs/5458310472

Proposed solution: Drop support for Python < 3.6 as `zope.paste` does not seem to be very widely used and we have to drop support for that ancient versions anyway in the future.

### PR DESCRIPTION
**Pull request by mgedmin**
Update to current version of meta/config, which also adds Python 3.10 support.

Run tox -e isort-apply to make tox -e lint happy.

Disable with-legacy-python because paste.deploy no longer supports Python < 3.6.

Closes #5.

### CODE REVIEW

**Comment by icemac** [comment]
Additionally ran through the steps described in https://www.zope.dev/developer/python2.html and added support for Python 3.11.

@mgedmin Would you mind creating a new release or give me (`icemac`) the necessary rights on PyPI?

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by mgedmin** [comment]
> @mgedmin Would you mind creating a new release or give me (icemac) the necessary rights on PyPI?

You have PyPI rights now.

**Comment by icemac** [comment]
@mgedmin Thank you. It was not that easy to accept the PyPI invitation. The result was https://github.com/pypi/warehouse/issues/12554. But now I gained access to the project on PyPI and will cut a release later on.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.paste/1.1.0/.

**Pull request merged**
